LOAD DATA INFILE 'E:/02PROJETS/P_Soutien_164/E-LoadData/exercices/t_editeurt_editeur.csv'
INTO TABLE t_editeur
CHARACTER SET utf8
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(ID, Nom);
