LOAD DATA INFILE 'E:/02PROJETS/P_Soutien_164/E-LoadData/exercices/t_sujet'
INTO TABLE t_sujet
CHARACTER SET utf8
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(ID, Nom);
